# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# bug 已修复 ../

# 测试内容 ……

site_name: 游戏和谐Wiki
site_url: https://ggame.gledos.science/
site_description: >-
  这里是收集许多的和谐游戏的百科，正在持续收录中。

repo_name: gledos/ggame
repo_url: https://github.com/gledos/ggame

theme:
  favicon: favicon.png
  icon:
    logo: material/microsoft-xbox-controller-off
    admonition:
      quote: bootstrap/cblb
  font: false
  palette:
  - media: "(prefers-color-scheme: light)"
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: 切换到暗模式
  - media: "(prefers-color-scheme: dark)"
    primary: blue
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: 切换到亮模式
  name: material
  custom_dir: overrides
  language: zh              # 中文，解决中文搜索问题
  features:
    # - search.highlight
    # - navigation.instant  # XHR 支持
    # - navigation.tracking # 自动锚点更新
    - navigation.indexes    # 文件夹下的 index.md 自动「连接」
    - header.autohide
    - navigation.top        # 回到顶部的按钮
    # - toc.integrate
    # - tabs                # 顶部选项卡/栏位

use_directory_urls: false   # gledos 不喜欢的 URL 风格，所以要关闭
edit_uri: ""                # 隐藏编辑按钮

markdown_extensions:
# - legacy_em               # 恢复 Markdown 的严格加重符号语义
- md_in_html                # HTML 内书写 Markdown
- attr_list                 # 增加 css-html 样式，例如按钮，比如图片定义大小，caption    https://python-markdown.github.io/extensions/attr_list/
# - legacy_attrs            # 增加 css-html 样式，已废弃，不推荐使用    https://python-markdown.github.io/extensions/legacy_attrs/
- admonition                # 突出显示一些东西，比如 !!!info|bug|tips之类
- footnotes                 # 支持脚注[^1]
- def_list                  # 支持有序、无序、任务列表
- pymdownx.superfences:     # 代码块相关
    custom_fences:          # 代码块相关
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- toc:
    permalink: "#"          # heading anchor
    slugify: !!python/name:pymdownx.slugs.uslugify     # 解决中文标题解析问题
- codehilite:
    guess_lang: false
    linenums: false
# - pymdownx.betterem:
#     smart_enable: all
- pymdownx.tabbed:        # 标签页 https://squidfunk.github.io/mkdocs-material/reference/content-tabs/ # C++/python 代码例子切换
    alternate_style: true
- meta                    # YAML 元数据
- pymdownx.tasklist
- pymdownx.details
- pymdownx.highlight      # 代码块相关
- pymdownx.inlinehilite   # 代码块相关
- pymdownx.snippets
# - pymdownx.magiclink    # 魔法链接，自动把裸露的链接转化成 <a> 标签
- pymdownx.mark
- pymdownx.critic         # 支持 markdown 高亮==、删除、注解等高级样式
- pymdownx.keys           # 支持 快捷键渲染
- pymdownx.emoji:         # 支持图标 icons 和表情渲染，比如:smile:
    # emoji_index: !!python/name:materialx.emoji.twemoji
    # emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
        - overrides/.icons
# pymdownx.b64            # 将图片编码为 base64
# - abbr                  # 缩写词，因为没有多少 Markdown 使用这样的语法，所以不会使用。
# - nl2br                 # newline-to-break markdown 非严格换行，我不喜欢的插件
# - pymdownx.arithmatex   # 数学公式latex支持
# - pymdownx.pathconverter:
#     base_path: ''       # default: ''
#     relative_path: ''   # default ''
#     absolute: false     # default: false
#     tags: 'a script img link object embed'
# - pymdownx.caret        # 上标、下划线
# - pymdownx.smartsymbols # 1st 2en 以及特殊符号
# - pymdownx.tilde        # 下标

plugins:
# - progress                # 显示构建状态，方便除错？    https://github.com/obuya/mkdocs-new-features-notifier
- mkdocs-video:           # 支持内嵌本地视频    https://pypi.org/project/mkdocs-video/
    is_video: True
    css_style:
      width: "100%"
      height: "100%"
- minify:                 # 将文件 minify 的插件   https://github.com/byrnereese/mkdocs-minify-plugin
    minify_html: true     # html 过多，导致生成时间变成了三倍……
    minify_js: true       # 只压缩 js 和 css 效果又不明显，所以不打算使用……
    minify_css: true
    htmlmin_opts:
      remove_comments: true
  #   js_files:
  #   - my/javascript/dir/file1.js
  #   css_files:
  #   - css/external_link_icon.css
  #   - css/footnotes.css
  #   - css/base.css
  #   - css/custom_admonitions.css
# - search:
# - exclude-search:
    # exclude:
    # - CODE_OF_CONDUCT.md
    # - tags.md
    # - warrant_canary.md
    # - 待办事项.md
    # - rule/*
    # - news_archive/*
    # - encryption/*
- tags:
    tags_file: tags.md
- callouts                # 微软风格的 admonition     https://github.com/sondregronas/mkdocs-callouts
- abs-to-rel              # 绝对路径转相对路径        https://pypi.org/project/mkdocs-abs-rel-plugin/
# - pdf-export            # 导出为 PDF 格式，不过对于此 Wiki 来说，耗时过多。
# - roamlinks             # 这是自动将链接转化为易于 mkdocs 的插件
# - autolinks
- exclude:
    glob:
    - "src/_HD_/*"
    - "mkdocs/本地/*"
    - "*.tmp"
    - "*.gz"
    - "encryption/*"
    - "liquid/*"
    # regex:
    # - '.*\.(tmp|bin|tar)$'
- blogging:
    features:
      tags:
        index_page: tags.md
        insert: bottom
    time_format: '%Y-%m-%d %H:%M:%S'
    meta_time_format: '%Y-%m-%dT%H:%M:%S'
    dirs: # The directories to be included
    - blog
    categories:
    - name: activities
      dirs:
      - activities
      size: 50
      template: overrides/custom-blog.html
    - name: allowlist
      dirs:
      - allowlist
      size: 50
      template: overrides/custom-blog.html
    - name: anti-censorship
      dirs:
      - anti-censorship
      size: 50
      template: overrides/custom-blog.html
    - name: blocklist
      dirs:
      - blocklist
      size: 50
      template: overrides/custom-blog.html
    - name: text
      dirs:
      - text
      size: 50
      template: overrides/custom-blog.html
    - name: catch_the_wind
      dirs:
      - catch_the_wind
      size: 50
      template: overrides/custom-blog.html
    - name: censorship
      dirs:
      - censorship
      size: 50
      template: overrides/custom-blog.html
    - name: company
      dirs:
      - company
      size: 50
      template: overrides/custom-blog.html
    - name: game
      dirs:
      - game
      size: 50
      template: overrides/custom-blog.html
    - name: meme
      dirs:
      - meme
      size: 50
      template: overrides/custom-blog.html
    - name: mkdocs
      dirs:
      - mkdocs
      size: 50
      template: overrides/custom-blog.html
    - name: news_archive
      dirs:
      - news_archive
      size: 50
      template: overrides/custom-blog.html
    - name: people
      dirs:
      - people
      size: 50
      template: overrides/custom-blog.html
    - name: punish
      dirs:
      - punish
      size: 50
      template: overrides/custom-blog.html
    - name: research
      dirs:
      - research
      size: 50
      template: overrides/custom-blog.html
    - name: rule
      dirs:
      - rule
      size: 50
      template: overrides/custom-blog.html
    - name: serviceprovider
      dirs:
      - serviceprovider
      size: 50
      template: overrides/custom-blog.html
    - name: software
      dirs:
      - software
      size: 50
      template: overrides/custom-blog.html
    - name: technology
      dirs:
      - technology
      size: 50
      template: overrides/custom-blog.html
    - name: sound
      dirs:
      - sound
      size: 50
      template: overrides/custom-blog.html
    - name: unclear
      dirs:
      - unclear
      size: 50
      template: overrides/custom-blog.html
    - name: video
      dirs:
      - video
      size: 50
      template: overrides/custom-blog.html
    - name: website
      dirs:
      - website
      size: 50
      template: overrides/custom-blog.html
- redirects:              # 重定向插件                https://github.com/datarobot/mkdocs-redirects
    redirect_maps:
      "website/立场新闻.md": "company/立场新闻.md"
      "software/National_Anti-fraud_Center.md": "censorship/国家反诈中心.md"
      "punish/APP侵害用户权益专项整治行动/APP侵害用户权益专项整治行动.md": "punish/APP侵害用户权益专项整治行动/index.md"
      "rule/上海市密室剧本杀内容备案管理规定.md": "rule/地区规范性文件/上海市密室剧本杀规定.md"
      "rule/中国音像与数字出版协会游戏出版工作委员会/网络游戏行业防沉迷自律公约.md": "rule/行业协会/网络游戏行业防沉迷自律公约.md"
      "rule/中国演出行业协会/演出行业演艺人员从业自律管理办法.md": "rule/行业协会/演出行业演艺人员从业自律管理办法.md"
      "rule/关于进一步清理整治不规范地名的通知.md": "rule/多部门/关于进一步清理整治不规范地名的通知.md"
      "activities/IJOY漫展.md": "activities/漫展/IJOY漫展.md"
      "activities/COMICUP_28.md": "activities/漫展/COMICUP.md"
      "activities/ComicDawn动漫展.md": "activities/漫展/ComicDawn动漫展.md"
      "movement/「明星相关的审查」.md": "activities/「明星相关的审查」.md"
      "movement/2014年东莞扫黄事件.md": "activities/2014年东莞扫黄事件.md"
      "movement/2020清朗专项行动.md": "activities/2020清朗专项行动.md"
      "movement/清朗·互联网用户账号运营乱象专项整治行动.md": "activities/清朗·互联网用户账号运营乱象专项整治行动.md"
      "movement/清朗·暑期未成年人网络环境整治.md": "activities/清朗·暑期未成年人网络环境整治.md"
      "movement/扫黄打非·净网2014.md": "activities/扫黄打非·净网2014.md"
      "movement/扫黄打非·净网2015.md": "activities/扫黄打非·净网2015.md"
      "movement/网络安全宣传周活动.md": "activities/网络安全宣传周活动.md"
      "hardware/宝塔面板.md": "software/宝塔面板.md"
      "hardware/红星系统.md": "software/红星系统.md"
      "hardware/Kindle.md": "company/Amazon/Kindle.md"
      "hardware/Smart_set-top_box.md": "rule/Smart_set-top_box.md"
      "hardware/Synology.md": "company/Synology.md"
      "hardware/WAPI.md": "technology/WAPI.md"
      "censorship/内容分级/游戏/CERO.md": "censorship/内容分级/游戏/コンピュータエンターテインメントレーティング機構.md"
      "censorship/内容分级/游戏/EOCS.md": "censorship/内容分级/游戏/コンピュータソフトウェア倫理機構.md"
      "website/新浪微博.md": "company/新浪/新浪微博.md"
      "website/新浪博客.md": "company/新浪/新浪博客.md"
      "book/~大家学系列口袋书.md": "text/~大家学系列口袋书.md"
      "book/DaGuoZhanYi.md": "text/DaGuoZhanYi.md"
      "book/Gate_Where_the_JSDF_Fought.md": "text/Gate_Where_the_JSDF_Fought.md"
      "book/index.md": "text/index.md"
      "book/RAIDEN-18.md": "text/RAIDEN-18.md"
      "book/The_Anarchist_Cookbook.md": "text/The_Anarchist_Cookbook.md"
      "book/「苏联相关」.md": "text/「苏联相关」.md"
      "book/东方文化西方语.md": "text/东方文化西方语.md"
      "book/倒退的帝国：朱元璋的成与败.md": "text/倒退的帝国：朱元璋的成与败.md"
      "book/农村发展论丛.md": "text/农村发展论丛.md"
      "book/南方周末.md": "text/南方周末.md"
      "book/我加载了恋爱游戏.md": "text/我加载了恋爱游戏.md"
      "book/海贼王.md": "text/海贼王.md"
      "book/游戏机实用技术.md": "text/游戏机实用技术.md"
      "book/电人N.md": "text/电人N.md"
      "book/疫记.md": "text/疫记.md"
      "book/财经天下周刊.md": "text/财经天下周刊.md"
      "book/邓小平时代.md": "text/邓小平时代.md"
      "book/字典词典/新编学生字典.md": "text/字典词典/新编学生字典.md"
      "book/字典词典/网络字典词典.md": "text/字典词典/网络字典词典.md"
      "book/字典词典/输入法的音标.md": "text/字典词典/输入法的音标.md"

extra:
  generator: false
  social:
  - icon: fontawesome/brands/telegram
    link: https://t.me/gledos_microblogging
  - icon: material/email-outline
    link: mailto:cngledos@gmail.com

extra_css:
- "css/external_link_icon.css"
- "css/footnotes.css"          # 脚注 CSS
- "css/base.css"               # 格式处理
- "css/custom_admonitions.css" # 自定义 Admonitions

# extra_javascript:
# - https://unpkg.com/mermaid/dist/mermaid.min.js

copyright: 使用了 <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a> 以及 Github Pages 生成并托管网站。<br>
