# official tutorial
# mkdocs-material: https://squidfunk.github.io/mkdocs-material/
# mkdocs: https://www.mkdocs.org/user-guide/configuration/
# bug 已修复 ../

# 测试内容 ……

site_name: 游戏和谐 Wiki
site_url: https://ggame.gledos.science/
# site_description: >-
#   这里是收集许多的和谐游戏的百科，正在持续收录中。

repo_name: gledos/ggame
repo_url: https://github.com/gledos/ggame

use_directory_urls: false   # gledos 不喜欢的 URL 风格，所以要关闭
edit_uri: ""                # 隐藏编辑按钮

theme:
  favicon: favicon.png
  icon:
    logo: material/microsoft-xbox-controller-off
    admonition:
      quote: custom/cblb
  font: false
  palette:
  - media: "(prefers-color-scheme: light)"
    primary: blue
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: 切换到暗模式
  - media: "(prefers-color-scheme: dark)"
    primary: blue
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: 切换到亮模式
  name: material
  custom_dir: overrides
  language: zh            # 中文，解决中文搜索问题
  features:
  - navigation.prune      # 导航修剪
  - content.tabs.link     # 同步内容选项卡（点击 A 选项卡后，其他的 A 选项卡也会自动被选择） https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#open-me-in-a-new-tab-
  - navigation.indexes    # 文件夹下的 index.md 自动「连接」
  - header.autohide
  - navigation.top        # 回到顶部的按钮
  # - search.highlight
  # - navigation.instant  # XHR 支持
  # - navigation.tracking # 自动锚点更新
  # - toc.integrate
  # - tabs                # 顶部选项卡/栏位

markdown_extensions:
# - legacy_em               # 恢复 Markdown 的严格加重符号语义
- md_in_html                # HTML 内书写 Markdown
- attr_list                 # 增加 css-html 样式，例如按钮，比如图片定义大小，caption    https://python-markdown.github.io/extensions/attr_list/
# - legacy_attrs            # 增加 css-html 样式，已废弃，不推荐使用    https://python-markdown.github.io/extensions/legacy_attrs/
- admonition                # 突出显示一些东西，比如 !!!info|bug|tips之类
- footnotes                 # 支持脚注[^1]
- def_list                  # 支持有序、无序、任务列表
- sane_lists                # 允许从任意数字开始的有序列表    https://python-markdown.github.io/extensions/sane_lists/
- pymdownx.superfences:     # 代码块相关
    custom_fences:          # 代码块相关
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
- toc:
    permalink: "#"          # heading anchor
    slugify: !!python/name:pymdownx.slugs.uslugify     # 解决中文标题解析问题
- codehilite:
    guess_lang: false
    linenums: false
# - pymdownx.betterem:
#     smart_enable: all
- pymdownx.tabbed:        # 标签页 https://squidfunk.github.io/mkdocs-material/reference/content-tabs/ # C++/python 代码例子切换
    alternate_style: true
    # slugify: !!python/object/apply:pymdownx.slugs.slugify
    #   kwds:
    #     case: lower
- meta                    # YAML 元数据
- pymdownx.tasklist
- pymdownx.details
- pymdownx.highlight      # 代码块相关
- pymdownx.inlinehilite   # 代码块相关
- pymdownx.snippets
# - pymdownx.magiclink    # 魔法链接，自动把裸露的链接转化成 <a> 标签
- pymdownx.mark
- pymdownx.critic         # 支持 markdown 高亮==、删除、注解等高级样式
- pymdownx.keys           # 支持 快捷键渲染
- pymdownx.emoji:         # 支持图标 icons 和表情渲染，比如:smile:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
    options:
      custom_icons:
        - overrides/.icons
# pymdownx.b64            # 将图片编码为 base64
# - abbr                  # 缩写词，因为没有多少 Markdown 使用这样的语法，所以不会使用。
# - nl2br                 # newline-to-break markdown 非严格换行，我不喜欢的插件
# - pymdownx.arithmatex   # 数学公式latex支持
# - pymdownx.pathconverter:
#     base_path: ''       # default: ''
#     relative_path: ''   # default ''
#     absolute: false     # default: false
#     tags: 'a script img link object embed'
# - pymdownx.caret        # 上标、下划线
# - pymdownx.smartsymbols # 1st 2en 以及特殊符号
# - pymdownx.tilde        # 下标

plugins:
- glightbox:               # 添加灯箱功能    https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox
    auto_caption: true
    background: none
- rss:
    locale: zh-hans
    abstract_delimiter: ""
    # abstract_chars_count: "-1"
    date_from_meta:
      as_creation: dateCreated
      as_update: date
      datetime_format: "%Y-%m-%dT%H:%M:%S"
    categories:
    - tags
    match_path: ".*"
    url_parameters:
      utm_source: "documentation"
      utm_medium: "RSS"
      utm_campaign: "feed-syndication"
    use_git: false
# - offline                 # 离线使用    https://squidfunk.github.io/mkdocs-material/setup/building-for-offline-usage/
# - typeset                 # 排版插件    https://squidfunk.github.io/mkdocs-material/reference/#configuration
# - progress                # 显示构建状态，方便除错？    https://github.com/obuya/mkdocs-new-features-notifier
- mkdocs-video:           # 支持内嵌本地视频    https://pypi.org/project/mkdocs-video/
    is_video: True
    css_style:
      width: "100%"
      height: "100%"
# - minify:                 # 将文件 minify 的插件   https://github.com/byrnereese/mkdocs-minify-plugin
#     minify_html: true     # html 过多，导致生成时间变成了三倍……
#     minify_js: true       # 只压缩 js 和 css 效果又不明显，所以不打算使用……
#     minify_css: true
#     htmlmin_opts:
#       remove_comments: true
  #   js_files:
  #   - my/javascript/dir/file1.js
  #   css_files:
  #   - css/external_link_icon.css
  #   - css/footnotes.css
  #   - css/base.css
  #   - css/custom_admonitions.css
- search:
    separator: '[\s\u200b\-]'
# - exclude-search:
    # exclude:
    # - CODE_OF_CONDUCT.md
    # - tags.md
    # - warrant_canary.md
    # - 待办事项.md
    # - rule/*
    # - news_archive/*
    # - encryption/*
- tags:
    tags_file: tags.md
- callouts:               # 微软风格的 admonition     https://github.com/sondregronas/mkdocs-callouts
    breakless_lists: false
- abs-to-rel              # 绝对路径转相对路径        https://pypi.org/project/mkdocs-abs-rel-plugin/
# - pdf-export            # 导出为 PDF 格式，不过对于此 Wiki 来说，耗时过多。
# - roamlinks             # 这是自动将链接转化为易于 mkdocs 的插件
# - autolinks
- exclude:
    glob:
    - "src/_HD_/*"
    - "mkdocs/本地/*"
    - "*.tmp"
    - "*.gz"
    - "encryption/*"
    - "liquid/*"
    - ".trash/*"
    - "templates/*"
    # regex:
    # - '.*\.(tmp|bin|tar)$'
- blogging:
    features:
      tags:
        index_page: tags.md
        insert: bottom
    time_format: '%Y-%m-%d %H:%M:%S'
    meta_time_format: '%Y-%m-%dT%H:%M:%S'
    dirs: # The directories to be included
    - blog
    categories:
    - name: activities
      dirs:
      - activities
      size: 50
      template: overrides/custom-blog.html
    - name: allowlist
      dirs:
      - allowlist
      size: 50
      template: overrides/custom-blog.html
    - name: anti-censorship
      dirs:
      - anti-censorship
      size: 50
      template: overrides/custom-blog.html
    - name: blocklist
      dirs:
      - blocklist
      size: 50
      template: overrides/custom-blog.html
    - name: text
      dirs:
      - text
      size: 50
      template: overrides/custom-blog.html
    - name: catch_the_wind
      dirs:
      - catch_the_wind
      size: 50
      template: overrides/custom-blog.html
    - name: censorship
      dirs:
      - censorship
      size: 50
      template: overrides/custom-blog.html
    - name: company
      dirs:
      - company
      size: 50
      template: overrides/custom-blog.html
    - name: game
      dirs:
      - game
      size: 50
      template: overrides/custom-blog.html
    - name: meme
      dirs:
      - meme
      size: 50
      template: overrides/custom-blog.html
    - name: mkdocs
      dirs:
      - mkdocs
      size: 50
      template: overrides/custom-blog.html
    - name: news_archive
      dirs:
      - news_archive
      size: 50
      template: overrides/custom-blog.html
    - name: people
      dirs:
      - people
      size: 50
      template: overrides/custom-blog.html
    - name: punish
      dirs:
      - punish
      size: 50
      template: overrides/custom-blog.html
    - name: research
      dirs:
      - research
      size: 50
      template: overrides/custom-blog.html
    - name: rule
      dirs:
      - rule
      size: 50
      template: overrides/custom-blog.html
    - name: serviceprovider
      dirs:
      - serviceprovider
      size: 50
      template: overrides/custom-blog.html
    - name: software
      dirs:
      - software
      size: 50
      template: overrides/custom-blog.html
    - name: technology
      dirs:
      - technology
      size: 50
      template: overrides/custom-blog.html
    - name: sound
      dirs:
      - sound
      size: 50
      template: overrides/custom-blog.html
    - name: unclear
      dirs:
      - unclear
      size: 50
      template: overrides/custom-blog.html
    - name: video
      dirs:
      - video
      size: 50
      template: overrides/custom-blog.html
    - name: website
      dirs:
      - website
      size: 50
      template: overrides/custom-blog.html
    - name: theme
      dirs:
      - theme
      size: 50
      template: overrides/custom-blog.html
- redirects:              # 重定向插件                https://github.com/datarobot/mkdocs-redirects
    redirect_maps:
      # 实名制相关
      "catch_the_wind/KOL_前台实名.md": "censorship/实名制.md#kol-前台实名显示"
      "catch_the_wind/KOL-前台实名.md": "censorship/实名制.md#kol-前台实名显示"
      "censorship/韩国的实名制.md":     "censorship/实名制.md#kol-前台实名显示#韩国的实名制"
      "rule/烟花实名制.md":             "censorship/实名制.md#烟花实名制"
      "rule/Sugar_Real_Name.md":        "censorship/实名制.md#白糖实名制"

      # 清朗相关
      "activities/2020清朗专项行动.md":                        "activities/清朗系列行动.md"
      "activities/清朗·互联网用户账号运营乱象专项整治行动.md": "activities/清朗系列行动.md"
      "activities/清朗·暑期未成年人网络环境整治.md":           "activities/清朗系列行动.md"
      "movement/2020清朗专项行动.md":                          "activities/清朗系列行动.md"
      "movement/清朗·互联网用户账号运营乱象专项整治行动.md":   "activities/清朗系列行动.md"
      "movement/清朗·暑期未成年人网络环境整治.md":             "activities/清朗系列行动.md"
      # 合并清朗相关
      "activities/清朗/2020清朗专项行动.md":                                              "activities/清朗系列行动.md"
      "activities/清朗/2024-年清朗系列专项行动.md":                                       "activities/清朗系列行动.md"
      "activities/清朗/清朗_2024年春节网络环境整治.md":                                   "activities/清朗系列行动.md"
      "activities/清朗/清朗·互联网用户账号运营乱象专项整治行动.md":                       "activities/清朗系列行动.md"
      "activities/清朗/清朗·商业网站平台和_自媒体_违规采编发布财经类信息专项整治工作.md": "activities/清朗系列行动.md"
      "activities/清朗/清朗·暑期未成年人网络环境整治.md":                                 "activities/清朗系列行动.md"

      # 反诈相关
      "company/Microsoft/aka.ms.md":            "censorship/国家反诈中心.md#错误情况"
      "software/白描证件照.md":                 "censorship/国家反诈中心.md#错误情况"
      "software/讯飞记笔记.md":                 "censorship/国家反诈中心.md#错误情况"
      "software/National_Anti-fraud_Center.md": "censorship/国家反诈中心.md"

      # 禁止未经审批的游戏主题
      "blocklist/关于禁售游戏的公告-京东.md": "theme/禁止未经审批的游戏主题.md"
      "censorship/禁止直播未经审批的游戏.md": "theme/禁止未经审批的游戏主题.md#禁止直播未经审批的游戏"
      "game/《如何防小玩家钻空子》.md":       "theme/禁止未经审批的游戏主题.md#禁止境外游戏报导"

      # SIM 卡相关
      "anti-censorship/MVNO.md":     "serviceprovider/sim_卡.md#mvno"
      "serviceprovider/giffgaff.md": "serviceprovider/sim_卡.md#giffgaff"
      "serviceprovider/HK_SIM.md":   "serviceprovider/sim_卡.md#香港"

      # 拼写相关〔似乎并不需要，因为会自动跳转，那么就不需要添加了〕
      # "game/Doki_Doki_Literature_Club.md": "game/doki_doki_literature_club.md"

      # 漫展相关
      "activities/漫展/2022武汉百合only.md": "activities/漫展.md#夏日祭事件"
      "activities/漫展/ComicDawn动漫展.md":  "activities/漫展.md#夏日祭事件"
      "activities/漫展/COMICUP.md":          "activities/漫展.md#夏日祭事件"
      "activities/漫展/IJOY漫展.md":         "activities/漫展.md#夏日祭事件"
      "activities/漫展/index.md":            "activities/漫展.md"
      "activities/ComicDawn动漫展.md":       "activities/漫展.md#夏日祭事件"
      "activities/COMICUP_28.md":            "activities/漫展.md#夏日祭事件"
      "activities/IJOY漫展.md":              "activities/漫展.md#夏日祭事件"

      # Apple
      "company/Apple/flag_emoji.md": "company/Apple/index.md#flag_emoji"

      # 其他
      "activities/「明星相关的审查」.md": "theme/明星相关的审查.md"
      "anti-censorship/网际飞梭.md": "anti-censorship/VPN/网际飞梭.md"
      "anti-censorship/ClashDotNetFramework.md": "anti-censorship/VPN/ClashDotNetFramework.md"
      "anti-censorship/GoAgent.md": "anti-censorship/VPN/GoAgent.md"
      "anti-censorship/Netch.md": "anti-censorship/VPN/Netch.md"
      "anti-censorship/Shadowsocks.md": "anti-censorship/VPN/Shadowsocks.md"
      "anti-censorship/SocksCap64.md": "anti-censorship/VPN/SocksCap64.md"
      "anti-censorship/TCPioneer.md": "anti-censorship/VPN/TCPioneer.md"
      "anti-censorship/Tor.md": "anti-censorship/VPN/Tor.md"
      "anti-censorship/Trojan-Qt5.md": "anti-censorship/VPN/Trojan_Qt5.md"
      "blocklist/文化部查处6款违法网络游戏和6家网络游戏运营商.md": "blocklist/文化部办公厅关于查处第一批违法网络游戏的通知.md"
      "book/「苏联相关」.md": "text/index.md#苏联相关"
      "book/~大家学系列口袋书.md": "text/~大家学系列口袋书.md"
      "book/财经天下周刊.md": "text/财经天下周刊.md"
      "book/倒退的帝国：朱元璋的成与败.md": "text/倒退的帝国：朱元璋的成与败.md"
      "book/邓小平时代.md": "text/邓小平时代.md"
      "book/电人N.md": "text/电人N.md"
      "book/东方文化西方语.md": "text/东方文化西方语.md"
      "book/海贼王.md": "text/海贼王.md"
      "book/南方周末.md": "text/南方周末.md"
      "book/农村发展论丛.md": "text/农村发展论丛.md"
      "book/我加载了恋爱游戏.md": "text/我加载了恋爱游戏.md"
      "book/疫记.md": "text/疫记.md"
      "book/游戏机实用技术.md": "text/游戏机实用技术.md"
      "book/字典词典/输入法的音标.md": "software/输入法.md"
      "book/字典词典/网络字典词典.md": "text/字典词典/网络字典词典.md"
      "book/字典词典/新编学生字典.md": "text/字典词典/新编学生字典.md"
      "book/DaGuoZhanYi.md": "text/DaGuoZhanYi.md"
      "book/Gate_Where_the_JSDF_Fought.md": "text/Gate_Where_the_JSDF_Fought.md"
      "book/index.md": "text/index.md"
      "book/RAIDEN-18.md": "text/RAIDEN-18.md"
      "book/The_Anarchist_Cookbook.md": "text/The_Anarchist_Cookbook.md"
      "censorship/技术/DNS污染.md": "censorship/技术/DNS_污染.md"
      "censorship/技术/TCP重置攻击.md": "censorship/技术/TCP_重置攻击.md"
      "censorship/内容分级/游戏/CERO.md": "censorship/内容分级/游戏/コンピュータエンターテインメントレーティング機構.md"
      "censorship/内容分级/游戏/EOCS.md": "censorship/内容分级/游戏/コンピュータソフトウェア倫理機構.md"
      "censorship/展示用户_IP_属地信息.md": "activities/展示用户_IP_属地信息.md"
      "company/Google/Gmail.md": "company/Google/index.md#Gmail"
      "company/Microsoft/Xbox_One.md": "company/Microsoft/xbox.md"
      "company/Pixiv.md": "company/pixiv.md"
      "company/Samsung/三星_Galaxy_Z_系列.md": "company/Samsung/index.md#修改-z-系列名称"
      "company/Samsung/HK_Phone.md": "company/Samsung/index.md#dns-问题"
      "company/Sony/PSN.md": "company/Sony/playstation.md#psn"
      "game/惩戒魅魔.md": "game/index.md#she_will_punish_them"
      "game/禁止快递游戏光盘.md": "serviceprovider/快递.md"
      "game/塞尔达传说_旷野之息.md": "company/任天堂/switch.md#游戏送审失败"
      "game/噬梦者.md": "game/大陆色情游戏.md"
      "game/因为版号而暂时下架_Steam_大陆区.md": "theme/因为版号而暂时下架_Steam_大陆区.md"
      "game/Richman_8.md": "game/大富翁.md"
      "hardware/宝塔面板.md": "software/宝塔面板.md"
      "hardware/红星系统.md": "software/红星系统.md"
      "hardware/Kindle.md": "company/Amazon/Kindle.md"
      "hardware/Smart_set-top_box.md": "serviceprovider/智能机顶盒.md"
      "hardware/Synology.md": "company/Synology.md"
      "hardware/WAPI.md": "technology/WAPI.md"
      "movement/「明星相关的审查」.md": "theme/明星相关的审查.md"
      "movement/2014年东莞扫黄事件.md": "activities/2014年东莞扫黄事件.md"
      "movement/扫黄打非·净网2014.md": "activities/扫黄打非·净网2014.md"
      "movement/扫黄打非·净网2015.md": "activities/扫黄打非·净网2015.md"
      "movement/网络安全宣传周活动.md": "activities/网络安全宣传周活动.md"
      "rule/关于进一步清理整治不规范地名的通知.md": "rule/多部门/关于进一步清理整治不规范地名的通知.md"
      "rule/上海市密室剧本杀内容备案管理规定.md": "rule/地区规范性文件/上海市密室剧本杀规定.md"
      "rule/中国演出行业协会/演出行业演艺人员从业自律管理办法.md": "rule/行业协会/演出行业演艺人员从业自律管理办法.md"
      "rule/中国音像与数字出版协会游戏出版工作委员会/网络游戏行业防沉迷自律公约.md": "rule/行业协会/网络游戏行业防沉迷自律公约.md"
      "rule/Smart_set-top_box.md": "serviceprovider/智能机顶盒.md"
      "technology/VPN.md": "anti-censorship/VPN/index.md"
      "text/「苏联相关」.md": "text/index.md#苏联相关"
      "theme/书籍审查主题.md": "text/index.md"
      "unclear/禁止兽人.md": "unclear/禁止人外.md"
      "website/立场新闻.md": "company/立场新闻.md"
      "website/面包多.md": "censorship/技术/clienthold.md"
      "website/新浪博客.md": "company/新浪/新浪博客.md"
      "website/新浪微博.md": "company/新浪/新浪微博.md"
      "website/Amazon.md": "company/Amazon/index.md"
      "website/remove.bg.md": "company/小米/MIUI.md#remove-bg"

      # "punish/APP侵害用户权益专项整治行动/APP侵害用户权益专项整治行动.md": "punish/APP侵害用户权益专项整治行动/index.md"  # 已经拆分到 gld 分站上，所以不再需要这个了。

extra:
  generator: false
  social:
  - icon: fontawesome/brands/telegram
    link: https://t.me/gledos_microblogging
  - icon: material/email-outline
    link: mailto:cngledos@gmail.com
  analytics:
    provider: google
    property: G-6NFWGJL748
  consent:
    cookies:
      github:
        name: GitHub
        checked: true
      analytics:
        name: Google Analytics
        checked: true
      custom:
        name: Google AdSense
        checked: true
    title: Cookie 设置
    description: >-
      ggame 使用 Cookie 实现 Google 广告、分析和 GitHub 连接功能，请根据情况选择允许或拒绝这些 Cookie。<br>
      完成设置后，也可以在网站底部的「更改 Cookie 设置」重新调整。
    actions:
      - accept
      - reject
      - manage

extra_css:
- "css/base.css"               # 格式处理
- "css/custom_admonitions.css" # 自定义 Admonitions
- "css/external_link_icon.css" # 外链
- "css/footnotes.css"          # 脚注 CSS

extra_javascript:
- js/consent.js
# - https://unpkg.com/mermaid/dist/mermaid.min.js

copyright: >
  使用了 <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a> 以及 Github Pages 生成并托管网站。<br>
  <a href="#__consent">更改 Cookie 设置</a>
